<!doctype html>
<html lang='es'>
	<head>
		<title>Batalla naval</title>
		<meta charset='utf-8'>
		<link rel='stylesheet' href='<?php echo base_url()?>/css/bootstrap.min.css'>
		<link rel='stylesheet' href='<?php echo base_url()?>/css/bn.css'>
		<link rel="stylesheet" href='<?php echo base_url()?>/js/ui/jquery-ui.css'>
		<script src='<?php echo base_url()?>/js/jquery.min.js'></script>
		<script src='<?php echo base_url()?>/js/bootstrap.min.js'></script>
		<script src='<?php echo base_url()?>/js/bn.js'></script>
		<script src="<?php echo base_url()?>/js/ui/jquery-ui.min.js"></script>
	</head>
	<body>		
		<?=$content?>

	</body>
</html>